[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_boilerplate = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elizabetheidelson/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
